### ISSUE TITLE
Change in organization of this repository

### ISSUE THREAD

**Issue by Parulshandilya** [Cybros/paper.lnmiit#12]
Folders are organized according to year and semester but we have a change in our curriculum. According to ACM there are many amendments made in course structure so file should be subject wise. 
Furthermore, the folders should contain material year wise. This structure can make this repo more organized.
Example : Folder P2
                                Year 12
                                Year 13
                                Year 14
                                Year 15
                                Year 16
                 Folder DSA
                                Year 12
                                Year 13
                                Year 14
                                Year 15
                                Year 16

**Comment by divyanshu-rawat** [comment]
@goyal-sidd  if possible please address this issue as well.
@Parulshandilya thanks for your suggestion :+1:

**Comment by sid22** [comment]
@Parulshandilya making folder structure subject first will be bad. Espcially for senior years with multiple electives. What we can do it add branche for all years. Therein we will just give links to all the subjects,we can have same link in 2 different semsters/years. For DS, we can add it for both 1st and 2nd year. That would be better.

**Comment by yashovardhan** [comment]
@divyanshu-rawat @goyal-sidd I don't think this issue is needed anymore; shall we close it?
