### ISSUE TITLE
Create year wise pages

### ISSUE THREAD

**Issue by sid22** [Cybros/paper.lnmiit#13]
we need minimum 4 pages right now. One for each year. Inside that make 2 sections one for each semester and give links to papers as they come. Make one simple template like the index page and copy it 4 times for all the years.

**Comment by divyanshu-rawat** [comment]
@goyal-sidd  keep up the good work :+1:

**Comment by punit-agarwal** [comment]
Worked on this,
Please check pull requests: year1.html, year2.html, year3.html, year4.html
The links are pointed to GitHub's paper.lnmiit's papers for respective semester.
