### ISSUE TITLE
Help Wanted in contibuting previous year papers.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Cybros/paper.lnmiit#2]
@goyal-sidd if possible please draft and forward an e-mail to LNMIIT google groups on behalf of cybros.

**Comment by sid22** [comment]
Email is sent to all UG groups.

**Comment by Parth910** [comment]
@divyanshu-rawat  sir i can't download previous year papers. what should i do?

**Comment by divyanshu-rawat** [comment]
@parthpatel4203  there is a green button on the right-hand side of the main repo. https://github.com/Cybros/paper.lnmiit in which download is written.
