### ISSUE TITLE
Option for downloading paper.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Cybros/paper.lnmiit#23]
It would be great if we download the paper for the website itself instead of redirecting the client to the GitHub repo. for instance what I mean to say is described below using snapshots.

![screenshot from 2017-09-13 21 17 37](https://user-images.githubusercontent.com/13464678/30387054-108cb6f2-98c9-11e7-83a6-31be87fc6b95.png)

![screenshot from 2017-09-13 21 17 47](https://user-images.githubusercontent.com/13464678/30387075-16beabfc-98c9-11e7-8590-39baf836b55f.png)

Hope you got the context.

@goyal-sidd  @yashovardhanagrawal  @nimbus1212 @punit-agarwal  any suggestions?

@yashovardhanagrawal  side-bar is missing from other pages. 
here we are missing framework because if we had leveraged a framework than we could have leveraged the power of templates and here are we are violating DRY principle and reinventing the wheel.

**Comment by punit-agarwal** [comment]
Sure sir,
We can proceed with it. We will now have to provide a download link on the website itself.

**Comment by divyanshu-rawat** [comment]
@goyal-sidd I am creating side version of this project in angular JS. :+1: 
In order to ensure template rerendering & DRY principle.

**Comment by punit-agarwal** [comment]
Made 16 HTML files, 2 for each semester. Shall I pull request for all of them?
I forgot to change patch while creating files, and now ended up with many patches :/

**Comment by yashovardhan** [comment]
I have improved the folder structure, but the thing of downloading papers cannot be directly done from the website unless a script is written that can trace the newly added papers and map them into a page which allows us to download the papers.

for now, the last path of downloading papers is still our GitHub repository unless someone commits that script.

**Comment by punit-agarwal** [comment]
@yashovardhanagrawal Well, I think we can just add a PDF file and give it a GitHub link. We can attach this link on HTML page itself
It would allow us to download
Check punitagarwal.me

**Comment by yashovardhan** [comment]
@punit-agarwal you might view the current system which I introduced in the latest merged PR. This is the best possible solution according to me in the current scenario. 
Don't you think downloading pdf for every link would be cumbersome?

**Comment by divyanshu-rawat** [comment]
@punit-agarwal  for now let's leave it as it is we will think about it in the future.

**Comment by amisha2016** [comment]
@divyanshu-rawat What I got to know from this issue is when we will click for papers for a particular branch like CSE then it should show list of all papers on the same page and just in front of it there should be download button to download the respective paper. Am I right? If no then let me know better insights of the project in order to proceed with the issue.

**Comment by divyanshu-rawat** [comment]
Hi, @amisha2016  I am glad that you want to contribute what do you want to know about the project?

**Comment by amisha2016** [comment]
@divyanshu-rawat Thanks for your appreciation. Actually, I was trying to understand the purpose of this issue and explained in the previous message. 

I can explain it in more detail now. 

Currently, In master branch
When we will reach to the page http://your-ip__address/paper.lnmiit/year1/sem1/sem1.html
There are options of all branches like CSE.

After modification
 In the same page it will display list of uploaded papers and just adjacent to each paper there will be download button to download paper. It will not point to github repo again and again. 

So, I was just asking Am I right in understanding the issue you created.

**Comment by divyanshu-rawat** [comment]
@amisha2016  I guess you are right but It would be great if you implement the working prototype. we would be more than happy to merge it.
Thanks 👍

**Comment by amisha2016** [comment]
@divyanshu-rawat 
What formats do you accept for question papers like pdf, docx. I mean to say is there any restriction on particular type formats of question papers are accepted.

**Comment by divyanshu-rawat** [comment]
@amisha2016  @aasthasona79 @Parulshandilya can help you they both are maintainers.

**Comment by divyanshu-rawat** [comment]
@amisha2016  I guess there is no restriction pdf, docs format will work.

**Comment by Parulshandilya** [comment]
yes one can upload in docs format its not been checked
