### ISSUE TITLE
Colour combination not suitable

### ISSUE THREAD

**Issue by yashovardhan** [Cybros/paper.lnmiit#29]
I think the colour combination of blue and white is not going well with the main black theme of the website.

**Comment by swarnim1212** [comment]
i am also feeling the same...should we change the change the colour of buttons @yashovardhanagrawal 
or we can have different theme

**Comment by ujjwal101040** [comment]
i think there should be a different theme @nimbus1212

**Comment by yashovardhan** [comment]
@nimbus1212 I was thinking of changing the buttons, for now, the theme can be changed gradually.

**Comment by yashovardhan** [comment]
@nimbus1212 great work! I think this issue needs to be closed now 😄
