### ISSUE TITLE
Add New Papers !

### ISSUE THREAD

**Issue by divyanshu-rawat** [Cybros/paper.lnmiit#41]
Add New Papers !

**Comment by akshatbhargava123** [comment]
@divyanshu-rawat  Hello, I want to work on this. But could you make it more clear, what I exactly have to do?

**Comment by amisha2016** [comment]
@divyanshu-rawat Can I add papers of my college?

**Comment by yashovardhan** [comment]
@amisha2016 sorry but this portal is for LNMIIT students to get a reference to their old papers. I don't think it's appropriate to upload papers of another college.
