### ISSUE TITLE
There should be an issue and PR template

### ISSUE THREAD

**Issue by ParthS007** [Cybros/paper.lnmiit#43]
I would like to add an issue and PR template as it will provide more clarity of the issue and PRs

**Comment by ParthS007** [comment]
your views @divyanshu-rawat ?

**Comment by divyanshu-rawat** [comment]
@ParthS007 👍

**Comment by yashovardhan** [comment]
Nice Work @ParthS007 

It would great if you can add similar templates in other repos also 😄
