### ISSUE TITLE
Major BUG: Paper Download Option Not Working

### ISSUE THREAD

**Issue by yashovardhan** [Cybros/paper.lnmiit#59]
**I'm submitting a ...**
- [x] bug report

**Current behavior:**
The PHP Script instead of showing the respective papers of every folder is being downloaded. You can check that out at [https://cybros.github.io/paper.lnmiit/](https://cybros.github.io/paper.lnmiit/)

**Expected behavior:**
It should show a page which will let us download the papers.

@amisha2016 you should check this issue here.

**Comment by ParthS007** [comment]
I think it is caused due to #58. Will check this

**Comment by divyanshu-rawat** [comment]
hey @amisha2016 look into this bug if you have time 👍

**Comment by amisha2016** [comment]
@yashovardhanagrawal It's working fine on my side. Are you doing it on Ubuntu or any other OS?
If Ubuntu then please send me the error.log file located in /var/log/apache2/error.log

**Comment by amisha2016** [comment]
@yashovardhanagrawal  @divyanshu-rawat I think github.io(i.e. Github Pages) don't run php. They are just for HTML or normal pages. The issue which we are talking for is not possible to solve with HTML only. So, there is necessity to include php. You may try it on your localhost once.

**Comment by divyanshu-rawat** [comment]
ya @amisha2016 it's for static content GitHub pages don't run PHP try deploying it to Heroku.

**Comment by amisha2016** [comment]
@divyanshu-rawat Have you tried it in Heroku. If it's not working then do let me know.

**Comment by punit-agarwal** [comment]
@amisha2016 I tried on Xampp LocalHost, and it's working pretty good there. People facing issues please share error log.

**Comment by amisha2016** [comment]
If it's working then I think we should close this issue. What say @divyanshu-rawat @punit-agarwal ?

**Comment by yashovardhan** [comment]
@amisha2016 I checked it on my localhost its working fine there...

But I think this issue should remain here as long as the GitHub Pages link is malfunctioning.

This website is meant to be hosted on GitHub pages currently so as long as we don't find any alternative to it, this issue should remain.
