### ISSUE TITLE
Add a page containing download links for folder contents (Use GitHub APIs)

### ISSUE THREAD

**Issue by yashovardhan** [Cybros/paper.lnmiit#69]
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**
Script is being downloaded

**Expected behaviour:**
Page must be loaded which contains the downloading links for all the papers uploaded in the specific folder.

**Steps to reproduce:**

1. Get familiar with the way papers are uploaded in the repository, it's quite simple just take a view of the folder structure.
2. Checkout GitHub Rest APIs or GraphQL APIs, there are APIs for almost anything in GitHub.
3. Delete the Current PHP Script, as it is not supported by GitHub Pages.
4. Make an HTML page using the Specific GitHub API and make copies of it in every folder wherever it is required.
5. Send us a PR for it 😄

**Comment by sid22** [comment]
Yes, great issue @yashovardhanagrawal . I too thought it was very wrong that scripts are being downloaded. How about we just directly link the PDFs, that way they open in the Chrome Viewer, people can easily download/view it that way.

**Comment by yashovardhan** [comment]
That's a great idea too

first let's wait for this issue to be solved, then we might open that one too 😄

**Comment by MohitDeshwal** [comment]
I am not getting the point. How and where are we trying to execute the PHP  script ?

**Comment by MohitDeshwal** [comment]
Got it! I am working on PR.

**Comment by yashovardhan** [comment]
@MohitDeshwal great, if there's any problem you can ask us anytime!

Also, the PHP script was just there to track the files present in that particular folder. I hope you got that. The script is running perfectly well on the localhost but fails to run on Github Pages. I think they do not support PHP scripts there.

You can find GitHub APIs here: https://developer.github.com/v3/

**Comment by yashovardhan** [comment]
@MohitDeshwal you PR was merged, please add that download page to other folders as well then we can close this issue
