### ISSUE TITLE
Extend the limitation of resources.

### ISSUE THREAD

**Issue by punit-agarwal** [Cybros/paper.lnmiit#8]
Can we broaden this repo by adding other materials related to semester like, notes, assignments, books, and other relevant documents?

**Comment by sid22** [comment]
We can, but at this stage. It would be better if we were to focus on question papers first and complete that part before the mid  sems. We can add more functionalities later as we work on the project in future versions. 

Great idea though Punit. Maybe after we complete the current work you take up a lead in developing these features?

**Comment by punit-agarwal** [comment]
Sure @goyal-sidd 
I would love to do that.
Also, thank you for considering me worthy.
